// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type UserClassAddReq struct {
}

type UserClassAddResp struct {
}

type UserClassDeleteReq struct {
}

type UserClassDeleteResp struct {
}

type UserClassReq struct {
}

type UserClassResp struct {
}

type UserClassUpdateReq struct {
}

type UserClassUpdateResp struct {
}
