// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type UserRoleAddReq struct {
}

type UserRoleAddResp struct {
}

type UserRoleDeleteReq struct {
}

type UserRoleDeleteResp struct {
}

type UserRoleReq struct {
}

type UserRoleResp struct {
}

type UserRoleUpdateReq struct {
}

type UserRoleUpdateResp struct {
}
