// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type UserInfoReq struct {
	ID int64 `path:"id"`
}

type UserInfoResp struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type UserInfoUpdateReq struct {
}

type UserInfoUpdateResp struct {
}

type UserLoginReq struct {
}

type UserLoginResp struct {
}
