// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	class "shorturl/apigroup/internal/handler/class"
	role "shorturl/apigroup/internal/handler/role"
	user "shorturl/apigroup/internal/handler/user"
	"shorturl/apigroup/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/class/add",
				Handler: class.UserClassAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/delete",
				Handler: class.UserClassDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/info",
				Handler: class.UserClassInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/list",
				Handler: class.UserClassListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/update",
				Handler: class.UserClassUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/role/add",
				Handler: role.UserRoleAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/delete",
				Handler: role.UserRoleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/info",
				Handler: role.UserRoleInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/list",
				Handler: role.UserRoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/update",
				Handler: role.UserRoleUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info/update",
				Handler: user.UserInfoUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
