// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGozeroShorturlsIdPrefix      = "cache:gozero:shorturls:id:"
	cacheGozeroShorturlsShortenPrefix = "cache:gozero:shorturls:shorten:"
)

type (
	shorturlsModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Shorturls) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []Shorturls) error
		FindOne(ctx context.Context, id uint64) (*Shorturls, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]Shorturls, int64, error)
		FindOneByShorten(ctx context.Context, shorten sql.NullString) (*Shorturls, error)
		Update(ctx context.Context, tx *gorm.DB, data *Shorturls) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Shorturls) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []Shorturls) error

		Delete(ctx context.Context, tx *gorm.DB, id uint64) error
	}

	defaultShorturlsModel struct {
		gormc.CachedConn
		table string
	}

	Shorturls struct {
		Id        uint64         `gorm:"column:id;primary_key"`
		CreatedAt sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt sql.NullTime   `gorm:"column:updated_at"`
		DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index"`
		Shorten   sql.NullString `gorm:"column:shorten"`
		Url       sql.NullString `gorm:"column:url"`
	}
)

func (Shorturls) TableName() string {
	return "`shorturls`"
}

func newShorturlsModel(db *gorm.DB, c cache.CacheConf) *defaultShorturlsModel {
	return &defaultShorturlsModel{
		CachedConn: gormc.NewConn(db, c),
		table:      "`shorturls`",
	}
}

func (m *defaultShorturlsModel) GetCacheKeys(data *Shorturls) []string {
	if data == nil {
		return []string{}
	}
	gozeroShorturlsIdKey := fmt.Sprintf("%s%v", cacheGozeroShorturlsIdPrefix, data.Id)
	gozeroShorturlsShortenKey := fmt.Sprintf("%s%v", cacheGozeroShorturlsShortenPrefix, data.Shorten)
	cacheKeys := []string{
		gozeroShorturlsIdKey, gozeroShorturlsShortenKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultShorturlsModel) Insert(ctx context.Context, tx *gorm.DB, data *Shorturls) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultShorturlsModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []Shorturls) error {

	err := batchx.BatchExecCtxV2(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		for _, v := range news {
			if err := db.Create(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)
	return err
}

func (m *defaultShorturlsModel) FindOne(ctx context.Context, id uint64) (*Shorturls, error) {
	gozeroShorturlsIdKey := fmt.Sprintf("%s%v", cacheGozeroShorturlsIdPrefix, id)
	var resp Shorturls
	err := m.QueryCtx(ctx, &resp, gozeroShorturlsIdKey, func(conn *gorm.DB) error {
		return conn.Model(&Shorturls{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultShorturlsModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]Shorturls, int64, error) {
	formatDB := func(conn *gorm.DB) (*gorm.DB, *gorm.DB) {
		db := conn.Model(&Shorturls{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}
	res, total, err := pagex.FindPageList[Shorturls](ctx, m, page, orderBy, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultShorturlsModel) FindOneByShorten(ctx context.Context, shorten sql.NullString) (*Shorturls, error) {
	gozeroShorturlsShortenKey := fmt.Sprintf("%s%v", cacheGozeroShorturlsShortenPrefix, shorten)
	var resp Shorturls
	err := m.QueryRowIndexCtx(ctx, &resp, gozeroShorturlsShortenKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&Shorturls{}).Where("`shorten` = ?", shorten).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShorturlsModel) Update(ctx context.Context, tx *gorm.DB, data *Shorturls) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultShorturlsModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Shorturls) error {
	clearData := make([]Shorturls, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtxV2(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		for _, v := range news {
			if err := db.Save(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)

	return err
}

func (m *defaultShorturlsModel) Delete(ctx context.Context, tx *gorm.DB, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Shorturls{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultShorturlsModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []Shorturls) error {
	err := batchx.BatchExecCtxV2(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		for _, v := range datas {
			if err := db.Delete(&v).Error; err != nil {
				return err
			}
		}
		return nil
	}, tx)
	return err
}

func (m *defaultShorturlsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGozeroShorturlsIdPrefix, primary)
}

func (m *defaultShorturlsModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Shorturls{}).Where("`id` = ?", primary).Take(v).Error
}
